language: python
services:
  - sqlite
python:
# - 2.7
# - 3.4
# - 3.5
# - 3.6
# - 3.7
env:
- DEPS='Django==1.11'
- DEPS='Django==1.11 boto3'
- DEPS='Django==2.0'
- DEPS='Django==2.0 boto3'
- DEPS='Django==2.1'
- DEPS='Django==2.1 boto3'
- DEPS='Django==2.2'
- DEPS='Django==2.2 boto3'
matrix:
  include:
  - python: 3.7
    dist: bionic
    env: DEPS='Django==2.2'
  exclude:
  - python: 2.7
    env: DEPS='Django==2.0'
  - python: 2.7
    env: DEPS='Django==2.0 boto3'
  - python: 2.7
    env: DEPS='Django==2.1'
  - python: 2.7
    env: DEPS='Django==2.1 boto3'
  - python: 2.7
    env: DEPS='Django==2.2'
  - python: 2.7
    env: DEPS='Django==2.2 boto3'
  - python: 3.4
    env: DEPS='Django==2.1'
  - python: 3.4
    env: DEPS='Django==2.1 boto3'
  - python: 3.4
    env: DEPS='Django==2.2'
  - python: 3.4
    env: DEPS='Django==2.2 boto3'
install:
- pip install -q mock $DEPS
script:
- python runtests.py
