language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
env:
- DEPS='Django==1.9'
- DEPS='Django==1.9 boto3'
- DEPS='Django==1.10'
- DEPS='Django==1.10 boto3'
- DEPS='Django==1.11'
- DEPS='Django==1.11 boto3'
- DEPS='Django==2.0'
- DEPS='Django==2.0 boto3'
matrix:
  exclude:
  - python: 2.7
    env: DEPS='Django=2.0' DEPS='Django=2.0 boto3'
install:
- pip install -q mock $DEPS
script:
- python runtests.py
deploy:
  provider: pypi
  user: bradleyg
  on:
    tags: true
  password:
    secure: a+Xq1e2yuTNtjcJ5wJ5oQxsfx/lqwYD7dbFEqdoazpkflZ8UA9AErgL2quAbo0RIRKFDBXwRNUspRtQdQ6TClKxgzsaa4AQEPWxYxx353kYMdhPjXe0/ib1rWJ0eefs/RDu0mndpQu/slNjxzV351QXPoPKo9tHgnLHWoNzYAzs=
